### ISSUE TITLE
POST /Books 

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#12]

**Comment by Fremonster** [comment]
Task 2: Update Swagger page to have JSON object as a parameter for API calls rather than form data. Also, put Maria's updated model in yaml file.

**Comment by Fremonster** [comment]
Task 2 is complete (2 hours). The updated yaml file has been committed to the swagger branch of the API repo. I also uploaded a swagger-ui-dist folder on that branch. If you download that folder to your computer and click on the index.html file, it will run our API documentation in the Swagger UI. It doesn't work in Chrome when running locally, but you can use Firefox or Edge. At some point, we'll want to incorporate this swagger documentation page into our project.

**Comment by Fremonster** [comment]
Task 4 complete (3 hours). Created a basic Azure Function to add a new book to Cosmos DB. I spent at least an hour trying to test my function locally with Function Core Tools and the Cosmos DB Emulator. However, I could not get my local testing environment to work correctly. I finally just deployed it to my Azure testing environment that Clint set up, and it worked fine. I created a collection in my testing Cosmos DB resource to store the books. I ran my function in Azure and was able to post a book to the collection. A lot of the time in this task was spent learning how to create and edit Azure functions in VS Code, understanding the different pieces of the Functions project, and learning about how all the parts work together.

**Comment by Fremonster** [comment]
My Post Books API call can be tested here:
http://www.apirequest.io/5c5af70d9dfa290001266f91?at=eyJhcHAiOiI1YzVhZjcwZDlkZmEyOTAwMDEyNjZmOTEiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIwOjAiLCJwZXJtaXNzaW9ucyI6eyIwOjAiOnsic2NwIjoiY3JlYXRlOndvcmtzcGFjZXMgcmVhZDp3b3Jrc3BhY2VzIHVwZGF0ZTp3b3Jrc3BhY2VzIGRlbGV0ZTp3b3Jrc3BhY2VzIn19LCJleHAiOjE1NTIwMDMyMDAsImp0aSI6IjA2ZGNiYTZiLWM2YjEtNGM2Zi05NzVhLTNlMDg4MTQ1MDdkMCJ9.4-QW-56Bn9-uIwuc2KaO3PIDGhIxoukB1klxz5a6lRA

Test with a Json book in this format:
{
  "title": "Cinderella",
  "description": "Cinderella is a folk tale embodying a myth-element of unjust oppression and triumphant reward.",
  "author": "Marcia Brown"
}

**Comment by Fremonster** [comment]
1. Working Implementation (more details on my wiki):
POST https://melanieoneboxfunctionsprint2.azurewebsites.net/v1/books
Send in the body: { "title": "Harry Potter", "description": "An orphaned 11 year old boy discovers he's a wizard.", "author": "J.K. Rowling" }
Returns a generated Book Id in this format: 4c1b1f99-c742-435b-a31e-fe1d2540568e

2. My wiki: https://github.com/MerryFairyTalesAD440/API/wiki/Post-Books

3. My Pull Request: https://github.com/MerryFairyTalesAD440/API/pull/36

4. Code review/testing - I reviewed Mikal's code and approved his pull request

5. Estimate time: 5 hours, Actual time: 11 hours
