### ISSUE TITLE
The URL for GET /books is wrong

### ISSUE THREAD

**Issue by toddysm** [MerryFairyTalesAD440/API#18]
Please fix the URL for your GET API to refer the resource and omit the verb

Task #16 

It should look like this https://merry-fairy-tales.azurewebsites.net/v1/books

Ideally we will have https://api.1edusite.com/v1/books

**Comment by mcontado** [comment]
Currently, this is the working implementation, verb omitted: 
https://merry-fairy-tales.azurewebsites.net/api/books

Trying to figure out how to add the `v1` as part of the url.
