### ISSUE TITLE
Investigate Azure functions for API

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#2]
@MikalViencek

**Comment by mviencek** [comment]
Begin investigating Azure functions.

**Comment by mviencek** [comment]
Created a sample api to test out Azure functions.  Azure functions seems pretty simple to use.  Great integration with VS 2017 Enterprise.  API can be accessed here
https://demofunctionsmikal-1-10-2019.azurewebsites.net/api/printname

printname function needs a name parameter as a query string or passed in as part of the body.  For example see the one below

https://demofunctionsmikal-1-10-2019.azurewebsites.net/api/printname?name=Dave

**Comment by mviencek** [comment]
simple sample api branch has been pushed for people to take a look at.  its located at https://github.com/MerryFairyTalesAD440/API/tree/mikal_sample_api
Do not merge branch into dev or prod! It's only a proof on concept for azure functions branch.

**Comment by mviencek** [comment]
Upload branch to github.  Branch name - mikal_sample_api.
Code comments added and function/variable names changed to match requirements.

**Comment by mviencek** [comment]
Haven't heard any negative feedback from UX group or API group.  Closing investigation of Azure functions.  I feel pretty confident we can use it to handle our api needs.

**Comment by mviencek** [comment]
Notified that I forgot to take CORS into account.  I forgot that the UX team would be accessing the test api through JavaScript.  Updated Functions API to accept request from *
Total time worked on API including research and updates - 6.5 hours
