### ISSUE TITLE
GET pulls from the Cosmos DB + DELETE Books

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#23]

**Comment by mcontado** [comment]
Begin investigating how to GET and DELETE /books into CosmosDB.
Total task time estimate 8 hrs.

**Comment by mcontado** [comment]
Task 1: Determine on how to connect to CosmosDB (Spent 4hrs)
Note: Connected by providing connection string. Need to find out how to integrate with Vault.

Helpful Links : 
https://code.visualstudio.com/docs/azure/mongodb
https://www.codementor.io/pmbanugo/working-with-mongodb-in-net-1-basics-g4frivcvz


Currently pulling data from CosmosDB: GET /books
https://merry-fairy-tales-cosmosdb.azurewebsites.net/v1/books

**Comment by mcontado** [comment]
PR: https://github.com/MerryFairyTalesAD440/API/pull/77

**Comment by mcontado** [comment]
For GET /books:
Able to fetch data from cosmosDB locally but getting 500 when deployed to azure. (I maybe missing some setup)

For DELETE /books/{bookid}:
Getting the following issue even though I already set the EnableCrossPartitionQuery to true for FeedOptions:
`(Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception.`

**Comment by mcontado** [comment]
WIKI page: https://github.com/MerryFairyTalesAD440/API/wiki/GET-and-DELETE-book
