### ISSUE TITLE
POST saves in the Cosmos DB + PUT Books

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#24]

**Comment by Fremonster** [comment]
1. I updated the Swagger page to have all the new API calls. It's on the swagger branch. This took about 2 hours (it's very finicky!).

**Comment by Fremonster** [comment]
2. I connected the POST /books function to the dev instance of Cosmos DB so that books are being saved in the database. The method returns the book id. I also created and deployed the first draft of my PUT /books/{bookid} function. It updates an existing book in the database. It will probably be most useful for adding the cover image or updating the basic info for the book like description. (4 hours).

**Comment by Fremonster** [comment]
3. Worked with Brad to try and call his create container function from within my post books function. However, I never got it to work, and Toddy recommended just using Brad's create container class as a library instead. So, I worked on getting that set up, but then I ran an to issues getting my key vault to work. Then after all that, my function app stopped working entirely and would only give me a 503 service unavailable error. So, I basically accomplished very little on Sunday. (5 hours)

**Comment by Fremonster** [comment]
4. Finally got the POST books function successfully calling Brad's code to create a container. Changed his function to being a Util class that I call in my function. The new storage container is created in the dev storage account. So, now the POST books function creates a new book in the dev Cosmos DB resource and then creates the container. It returns the id of the new book. I also updated my PUT books function. It updates and existing book. Right now it returns the updated book, but I will likely change this to just return a success message later. Right now my connections to the DB and storage are just via the application settings saved in Azure. For next sprint, I will get the key vault working.

**Comment by Fremonster** [comment]
1. Working implementation urls:
POST https://melanieoneboxfunctionsprint3.azurewebsites.net/v1/books
PUT https://melanieoneboxfunctionsprint3.azurewebsites.net/v1/books/{bookid} 
My branch: https://github.com/MerryFairyTalesAD440/API/tree/post-put-books
2. Wiki: https://github.com/MerryFairyTalesAD440/API/wiki/POST-Books-connected-to-DB-and-Storage-and-PUT-Books
3. Pull request: https://github.com/MerryFairyTalesAD440/API/pull/76
4. Bug/Testing: https://github.com/MerryFairyTalesAD440/API/issues/75
5. Estimated time: 8 hours, Actual time spent: 15 hours
