### ISSUE TITLE
@MelanieShaffer - Look into Swagger for the API

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#3]

**Comment by Fremonster** [comment]
Completed tasks:
1) Reviewed Maria's models
2) Looked at an example yaml file

**Comment by Fremonster** [comment]
Tasks completed:
1. Met with Maria and Jeremiah to discuss the data models, the wireframes for our UI, and what API rest calls are needed. (2 hours)
2. Drafted swagger yaml file. (3 hours)

**Comment by Fremonster** [comment]
Here is the draft Swagger yaml file for our API. For some reason, yaml files cannot be attached here, so I have changed the file type to txt. Just change the extension back to .yaml or copy and paste the text into the Swagger Editor: https://editor.swagger.io/

[https://app.zenhub.com/files/164904149/ddc12628-5554-4297-9efa-c87e49666cc2/download](https://app.zenhub.com/files/164904149/ddc12628-5554-4297-9efa-c87e49666cc2/download)

**Comment by Fremonster** [comment]
Path to the yaml file on my branch in github:
https://github.com/MerryFairyTalesAD440/API/blob/swagger/MerryFairyTalesAPI.yaml

**Comment by Fremonster** [comment]
My wiki page:
https://github.com/MerryFairyTalesAD440/API/wiki/Swagger-yaml-file
