### ISSUE TITLE
Get method for SAS token API should return Method Not Allowed response

### ISSUE THREAD

**Issue by toddysm** [MerryFairyTalesAD440/API#38]
Tested #13 according to the steps described in the https://github.com/MerryFairyTalesAD440/API/wiki/Get-SAS-Tokens

I tried to do GET https://merryfairytales.azurewebsites.net/v1/sastoken and got the following response 

![image](https://user-images.githubusercontent.com/1007103/53461926-febc4480-39f6-11e9-8b77-e0b6d7dfd363.png)

Here is also CURL response:
$ curl -v "https://merryfairytales.azurewebsites.net/v1/sastoken"
* STATE: INIT => CONNECT handle 0x600057a30; line 1404 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x600057a30; line 1440 (connection #0)
*   Trying 13.77.160.237...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x600057a30; line 1521 (connection #0)
* Connected to merryfairytales.azurewebsites.net (13.77.160.237) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x600057a30; line 1573 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x600057a30; line 1587 (connection #0)
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.azurewebsites.net
*  start date: Dec 17 12:40:47 2017 GMT
*  expire date: Dec 17 12:40:47 2019 GMT
*  subjectAltName: host "merryfairytales.azurewebsites.net" matched cert's "*.azurewebsites.net"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 4
*  SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x600057a30; line 1608 (connection #0)
> GET /v1/sastoken HTTP/1.1
> Host: merryfairytales.azurewebsites.net
> User-Agent: curl/7.59.0
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x600057a30; line 1670 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x600057a30; line 1795 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x600057a30; line 1811 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 404 Not Found
* Server Microsoft-IIS/10.0 is not blacklisted
< Server: Microsoft-IIS/10.0
< Set-Cookie: ARRAffinity=620f1df44aea834dab68c7412cb0f50e9e658f03129c693b6b3b017c7e892f08;Path=/;HttpOnly;Domain=merryfairytales.azurewebsites.net
< X-Powered-By: ASP.NET
< Set-Cookie: ARRAffinity=a1d21e8439d9fb9db8d3b8e0abbb83456be2f33bebc8f1f8f2311bb75283dd8a;Path=/;HttpOnly;Domain=merryfairytales.azurewebsites.net
< Date: Wed, 27 Feb 2019 02:48:08 GMT
< Content-Length: 0
<
* STATE: PERFORM => DONE handle 0x600057a30; line 1980 (connection #0)
* multi_done
* Connection #0 to host merryfairytales.azurewebsites.net left intact
* Expire cleared

toddysm@toddysm-mactb ~

Expectation is that I receive HTTP error 405 Method not allowed.

**Comment by mviencek** [comment]
Revise code to return a 405 if any method other than post is allowed.  Tested locally, deployed, and tested live.  Works.

Total time - 1hr
