### ISSUE TITLE
Unauthorized error returned 

### ISSUE THREAD

**Issue by mviencek** [MerryFairyTalesAD440/API#44]
Tried to use your curl command and an error was returned.
Curl command used -

curl -X POST -d "{ 'id':'0', 'title' : 'Cinderella','description' : 'childrens book','author':'random author' }" -v -i "https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/api/writeDoc"

Response received -

C:\Users\mvien>curl -X POST -d '{
curl: no URL specified!
curl: try 'curl --help' for more information

C:\Users\mvien> "id":"0",
The filename, directory name, or volume label syntax is incorrect.

C:\Users\mvien> "title" : "Cinderella",
'"title"' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mvien> "description" : "children'\''s book",
'"description"' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\mvien> "author":"random author"
The filename, directory name, or volume label syntax is incorrect.

C:\Users\mvien>curl -X POST -d "{ 'id':'0', 'title' : 'Cinderella','description' : 'childrens book','author':'random author' }" -v -i "https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/api/writeDoc"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 13.66.226.80...
* TCP_NODELAY set
* Connected to ad4401boxfransprint263s2plkbwxejg.azurewebsites.net (13.66.226.80) port 443 (#0)
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 216 bytes...
* schannel: sent initial handshake data: sent 216 bytes
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5120 length 5120
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 445
* schannel: encrypted data buffer: offset 5565 length 6144
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 6144
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> POST /api/writeDoc HTTP/1.1
> Host: ad4401boxfransprint263s2plkbwxejg.azurewebsites.net
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 94
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 94 out of 94 bytes
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 165
* schannel: encrypted data buffer: offset 165 length 103424
* schannel: decrypted data length: 136
* schannel: decrypted data added: 136
* schannel: decrypted data cached: offset 136 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 136 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 136
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
< Date: Wed, 27 Feb 2019 16:15:58 GMT
Date: Wed, 27 Feb 2019 16:15:58 GMT

**Comment by FrancescoWard** [comment]
Thank you @mviencek for reporting this issue. The function auth. level has been switched to "Anonymous". Please try again if possible.
Thanks & regards,
Francesco

**Comment by mviencek** [comment]
Returns a 404 error

curl -X POST -d "{ 'id':'0', 'title' : 'Cinderella','description' : 'childrens book','author':'random author' }" -v -i "https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/api/writeDoc"

Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\mvien>curl -X POST -d "{ 'id':'0', 'title' : 'Cinderella','description' : 'childrens book','author':'random author' }" -v -i "https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/api/writeDoc"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 13.66.226.80...
* TCP_NODELAY set
* Connected to ad4401boxfransprint263s2plkbwxejg.azurewebsites.net (13.66.226.80) port 443 (#0)
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 216 bytes...
* schannel: sent initial handshake data: sent 216 bytes
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5120 length 5120
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 445
* schannel: encrypted data buffer: offset 5565 length 6144
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 6144
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> POST /api/writeDoc HTTP/1.1
> Host: ad4401boxfransprint263s2plkbwxejg.azurewebsites.net
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 94
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 94 out of 94 bytes
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 162
* schannel: encrypted data buffer: offset 162 length 103424
* schannel: decrypted data length: 133
* schannel: decrypted data added: 133
* schannel: decrypted data cached: offset 133 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 133 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 133
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
< Date: Wed, 27 Feb 2019 23:17:14 GMT
Date: Wed, 27 Feb 2019 23:17:14 GMT
< Content-Length: 0
Content-Length: 0

<
* Connection #0 to host ad4401boxfransprint263s2plkbwxejg.azurewebsites.net left intact

C:\Users\mvien>curl -X POST -d "{ 'id':'0', 'title' : 'Cinderella','description' : 'childrens book','author':'random author' }" -v -i "https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/api/writeDoc"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 13.66.226.80...
* TCP_NODELAY set
* Connected to ad4401boxfransprint263s2plkbwxejg.azurewebsites.net (13.66.226.80) port 443 (#0)
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 216 bytes...
* schannel: sent initial handshake data: sent 216 bytes
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5120 length 5120
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 445
* schannel: encrypted data buffer: offset 5565 length 6144
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 6144
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with ad4401boxfransprint263s2plkbwxejg.azurewebsites.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> POST /api/writeDoc HTTP/1.1
> Host: ad4401boxfransprint263s2plkbwxejg.azurewebsites.net
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Length: 94
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 94 out of 94 bytes
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 162
* schannel: encrypted data buffer: offset 162 length 103424
* schannel: decrypted data length: 133
* schannel: decrypted data added: 133
* schannel: decrypted data cached: offset 133 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 133 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 133
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
< Date: Wed, 27 Feb 2019 23:17:23 GMT

**Comment by FrancescoWard** [comment]
HI @mviencek ,
Are you running on Win64 ? Can you please try the following from Windows cmd prompt (escaping the double quotes)?
```
curl -X POST -d '{ 
 \"id\":\"0\", 
 \"title\" : \"Cinderella\", 
 \"description\" : \"children'\''s book\", 
\"author\":\"random author\" 
}' -v -i 'https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/v1/writeDoc'
```
Thanks,
Francesco

**Comment by mviencek** [comment]
the content of a post should have nothing to do with a 404 error unless you set it up that way
the curl command you sent me does not compile

see below

C:\Users\mvien>curl -X POST -d '{ \"id\":\"0\", \"title\" : \"Cinderella\", \"description\" : \"children'\''s book\", \"author\":\"random author\" }' -v -i 'https://ad4401boxfransprint263s2plkbwxejg.azurewebsites.net/v1/writeDoc'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "id":"0",/
* Port number ended with '"'
* Closing connection -1
curl: (3) Port number ended with '"'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "title"/
* Could not resolve host: "title"
* Closing connection 0
curl: (6) Could not resolve host: "title"
Note: Unnecessary use of -X or --request, POST is already inferred.
* Bad URL, colon is first character
* Closing connection -1
curl: (3) Bad URL, colon is first character
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "Cinderella",/
* Could not resolve host: "Cinderella",
* Closing connection 1
curl: (6) Could not resolve host: "Cinderella",
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "description"/
* Could not resolve host: "description"
* Closing connection 2
curl: (6) Could not resolve host: "description"
Note: Unnecessary use of -X or --request, POST is already inferred.
* Bad URL, colon is first character
* Closing connection -1
curl: (3) Bad URL, colon is first character
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "children'\''s/
* Could not resolve host: "children'\''s
* Closing connection 3
curl: (6) Could not resolve host: "children'\''s
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: book",/
* Could not resolve host: book",
* Closing connection 4
curl: (6) Could not resolve host: book",
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: "author":"random/
* Port number ended with '"'
* Closing connection -1
curl: (3) Port number ended with '"'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: author"/
* Could not resolve host: author"
* Closing connection 5
curl: (6) Could not resolve host: author"
curl: (3) [globbing] unmatched close brace/bracket in column 1
Note: Unnecessary use of -X or --request, POST is already inferred.
* Protocol "'https" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol "'https" not supported or disabled in libcurl

**Comment by mviencek** [comment]
you dont have to escape quotes you just go to ' inside of "

**Comment by FrancescoWard** [comment]
Hi @mviencek,
thank you for this. Can you please try the command above again (I changed the quotes :-))

**Comment by mviencek** [comment]
That works.  Thank you.  I noticed that the url is different from the original curl submission.  you might want to update your issues and wiki

**Comment by FrancescoWard** [comment]
Thank you for this ! Will do.
