### ISSUE TITLE
ideally the classes for our functions should be in a "Classes" directory not "Functions" ?

### ISSUE THREAD

**Issue by FrancescoWard** [MerryFairyTalesAD440/API#52]
Not sure if this could work, but would it be possible to refactor our "develop" branch folder structure to have an additional "Classes" or "Objects" directory for anything that isn't a runnable function (such as "Book", "Page", ...)?

**Comment by mviencek** [comment]
Everything is a class.  Naming something a "class" folder is redundant and this is something better posted in the room for the group to decide.  I'm fine putting the book classes in a folder but it's not my decision.
