### ISSUE TITLE
Wrong error code (500) when book is not in the DB.

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#78]
If you query the DB and the "document" is empty, you should return a 404. I think right now it would return a 500 when you say document.ElementAt(0) if nothing if the count is 0. You can see my code for reference. I just did this. https://github.com/MerryFairyTalesAD440/API/blob/feat/GET-DELETE-PagesAndLangs/Functions/GetDeleteLanguage.cs It's on line 51.

#23

**Comment by mcontado** [comment]
Fixed as part of this Pull Request: https://github.com/MerryFairyTalesAD440/API/pull/84/files
